<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Please contact us if you think this is a server error. Thank you.' => 'Vui lòng liên hệ với chúng tôi nếu bạn cho rằng đây là lỗi máy chủ. Cảm ơn bạn.',
    'The above error occurred while the Web server was processing your request.' => 'Lỗi trên xảy ra trong khi máy chủ Web đang xử lý yêu cầu của bạn.',
    'The requested page does not exist.' => 'Trang yêu cầu không tồn tại.',
];
